export const ACTIONS = {
    FETCH_INIT: 'FETCH_INIT',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
    SET_QUERY: 'SET_QUERY',
    SET_FILTERS: 'SET_FILTERS',
    SET_WATCHLIST: 'SET_WATCHLIST',
    ADD_WATCHLIST: 'ADD_WATCHLIST',
    REMOVE_WATCHLIST: 'REMOVE_WATCHLIST',
    CLEAR_WATCHLIST: 'CLEAR_WATCHLIST',
    SET_PAGE: 'SET_PAGE',
    SET_SELECTED_SHOW: 'SET_SELECTED_SHOW'
};